noti-rs/noti

- src/core.rs
- src/data/dbus.rs
- src/data/notification.rs
- src/dbus/server.rs
- src/render.rs
- src/render/layer.rs
Moved to single window instance with inner actions. Added possibility to dismiss notifications by left button click and by timeout if possible.
Also added possibility to close notifications by method `CloseNotification` from D-Bus.
> Rewrite the usage of wayland-client code

- Cargo.lock
- Cargo.toml
- src/backend/mod.rs
- src/backend/render.rs
- src/backend/render/banner.rs
- src/backend/render/border.rs
- src/backend/render/color.rs
- src/backend/render/font.rs
- src/backend/render/image.rs
- src/backend/render/layer.rs
- src/backend/render/text.rs
- src/backend/render/types.rs
- src/backend/render/widget.rs
- src/backend/render/window.rs
- src/backend/window.rs
- src/backend/window_manager.rs
- src/config/mod.rs
- src/config/spacing.rs
The current state of the code is very difficult to maintain so need refactor for easing adding new features and detecting bugs. Here below a list of the actions which need to be done before merging to main branch. It can growth by new upcoming tasks.
> Overhaul refactor the render codebase

- Cargo.lock
- Cargo.toml
- crates/backend/src/render/banner.rs
- crates/backend/src/render/color.rs
- crates/backend/src/render/font.rs
- crates/backend/src/render/image.rs
- crates/backend/src/render/text.rs
- crates/backend/src/render/widget.rs
- crates/backend/src/window.rs
- crates/backend/src/window_manager.rs
- crates/config/Cargo.toml
- crates/config/src/colors.rs
- crates/config/src/lib.rs
- crates/config/src/text.rs
- crates/macros/.gitignore
- crates/macros/Cargo.toml
- crates/macros/src/lib.rs
Because of the current code in the config crate is horrible to maintain I invented time to write derive macro which must reduce the code amount and grow it in more effective way.
I'll write documentation and README file for this macro a little bit later.
> refactor: use `ConfigProprety` derive macro for more pleasant config maintainment

- crates/backend/src/render/banner.rs
- crates/backend/src/render/border.rs
- crates/backend/src/render/image.rs
- crates/backend/src/render/widget.rs
- crates/config/src/lib.rs
- Added `DrawColor::Transpasent(Coverage)` for changing background color by coverage factor;
- Instead of transferring background color to all widgets uses real background color by getting from framebuffer;
- Extended Border impl with new methods - `compile` and `get_color_at`, which is very helpful for image rounding;
- Added property `display.image.rounding` which accepts `u8` integer and used as border radius for image. (Default value: 0).
> feat: add image rounding by config property

- Cargo.lock
- crates/app/cli.rs
- crates/backend/src/lib.rs
- crates/backend/src/render.rs
- crates/config/Cargo.toml
- crates/config/src/lib.rs
- crates/config/src/watcher.rs
Now user can define a path to config file using `-c` or `--config` flag.
Also I changed scope of `Config` struct from global to function-local for reducing further errors with `std::sync::Mutex<T>`.
> feat: use user defined path to config file

- crates/backend/src/render/banner.rs
- crates/backend/src/render/text.rs
- crates/backend/src/render/types.rs
- crates/backend/src/render/widget.rs
- crates/config/src/spacing.rs
The `Container` type is unbounded that means inner widget containers will fill available space which is not good for particular cases. Especially in future, where we can add custom layout by filetype.
So this changes have solution via 'max-width` and `max-height`.
Adds `max-width` and `max-height` for `FlexContainer`. Also I've changed name from `Container` to `FlexContainer` which makes more sense.
With this I've fixed some mistakes with overflowing and ellipsization that have found during development.
> feat: make `FlexContainer` more flexible

- README.md
- crates/backend/src/banner.rs
- crates/backend/src/cache.rs
- crates/backend/src/render.rs
- crates/backend/src/window.rs
- crates/backend/src/window_manager.rs
- crates/config/src/color.rs
- crates/config/src/display.rs
- crates/config/src/general.rs
- crates/config/src/lib.rs
- crates/config/src/text.rs
- crates/config/src/theme.rs
- crates/filetype/src/converter.rs
- crates/render/src/color.rs
- crates/render/src/image.rs
- crates/render/src/widget.rs
- crates/shared/src/cached_data.rs
- crates/shared/src/file_watcher.rs
- crates/shared/src/lib.rs
- docs/ConfigProperties.md
At begin of development of the application there was not complex configuration, just simple and single TOML file. But since we feeding this application by coolest features, the config file becomes very complex.
To simplify this process, need to separate single config file into smaller. And I begin from colors.
I decided that we shouldn't save backward compatibility in this case because we aim to simplicity. So previous config values will be deprecated and removed from parsing.
Also there is other breaking change - I've moved the `font_size` property (previously unnamed) from `general.font` into `TextProperty`. It is more convenient and logic to use font size per text field instead of using global font size.
> feat: add `import` of config files and introduce color theme

- Cargo.lock
- crates/app/cli.rs
- crates/backend/Cargo.toml
- crates/backend/src/lib.rs
- crates/backend/src/scheduler.rs
- crates/client/src/lib.rs
- crates/dbus/src/actions.rs
- crates/dbus/src/notification.rs
- crates/dbus/src/server.rs
This pull-request implements the feature discussed in #32
It adds support for scheduling notifications with the `--schedule` flag in the `send` command.
- Human readable duration (e.g., "2 hours", "10 minutes", "1m 25s")
- `%d.%m.%Y %H:%M` — 01.01.2025 00:00
- `%d-%m-%Y %H:%M` — 01-01-2025 00:00
- `%Y.%m.%d %H:%M` — 2025.01.01 00:00
- `%Y-%m-%d %H:%M` — 2025-01-01 00:00
- `%d.%m.%Y %I:%M %p` — 01.01.2025 12:00 AM
- `%d-%m-%Y %I:%M %p` — 01-01-2025 12:00 AM
- `%Y.%m.%d %I:%M %p` — 2025.01.01 12:00 AM
- `%Y-%m-%d %I:%M %p` — 2025-01-01 12:00 AM
- `%H:%M` — 18:45
- `%I:%M %p` — 06:45 PM
- `RFC 3339`/`ISO 8601` UTC string
```rs
noti send --schedule "30 minutes" "Reminder" "Take a break" --timeout 0
```
> feat: notification scheduler

- crates/backend/src/window.rs
- crates/config/src/display.rs
- docs/ConfigProperties.md
Now supported extended syntax for `display.timeout` property and the previous configuration will be saved.
**Example of extended syntax**:
```toml
[display.timeout]
default = 3000 # for low and normal urgencies the timeout value will be applied
critical = 0 # but for critical urgency the timeout value will be ovirriden
[display.timeout]
default = 5000 # will be not used
low = 3000
normal = 4000
critical = 0
```
> feat: extend the timeout property to set per urgency

- crates/backend/src/lib.rs
- crates/backend/src/render.rs
- crates/backend/src/window.rs
- crates/backend/src/window_manager.rs
- crates/render/src/font.rs
The font doesn't reloads when the config file updates because of expensiveness. I mean that some font files are large like nerd-fonts. So I decided do it more later. Now I think the application is ready to reload fonts.
I figured out that there is not need to use `Arc<T>` because it is enough to throw the `Renderer` initialization into child thread and initialize the `InternalChannel` separately. So, now in the renderer module uses `Rc<RefCell<T>>` which is faster than atomic analogues.
With it I've added the font reload after checking the font name. If the font names are same, font won't reload.
> feat: reload font by updating config and use `Rc` instead of `Arc`s

- crates/config/src/display.rs
I found that the timeout value parses incorrectly from `display.timeout` as `u16` because of `serde`s specific internal work.
Added new method for `TimeoutVisitor` that accepts the `i64` value and converts into correct timeout value after clamping.
> fix: correct timeout value parsing

- crates/backend/src/backend_manager.rs
- crates/backend/src/idle_manager.rs
- crates/backend/src/idle_notifier.rs
- crates/backend/src/internal_messages.rs
- crates/backend/src/lib.rs
- crates/backend/src/window.rs
- crates/backend/src/window_manager.rs
Closes #79
With it also renamed important structs like `Renderer` -> `BackendManager` and it was made for better understanding of backend crate.
> fix: make idle_threshold watchable and not block loop when idled

- crates/app/cli.rs
- crates/client/src/lib.rs
One more reason to use our client application. Closes #76 
Added a way to print returned notification id into stdout. Flags: `-p` and `--print-id`.
> feat: add --print-id flag to print notification id into stdout

- crates/render/src/text.rs
When a text was sent with line breaks due some reasons. Usually it made for structuring. But the application doesn't handle this case, so it ended up not beautiful result. Text which should be separated into paragraphs looks like single massive paragraph.
Now the text with line breaks separates into paragraphs correctly. The ellipsization rule works as previously, but here adds a new rule - "If line from next paragraph cannot be ellipsized, then don't include the words from next paragraph to current and put ellipsis to the last line with word removal if needed".
> fix: introduce paragraphs to handle line breaks in text

- crates/backend/src/window.rs
- crates/backend/src/window_manager.rs
Notification which should be replaced by id doesn't replaces because it stores in notification queue. And a lot of time will pass before the replacement will show.
Replace the notifications by-pass `general.limit` option using direct call `replace_by_indices` methods.
> fix: replace notifications bypass general.limit

- crates/backend/src/idle_notifier.rs
In current code the `IdleNotification` object will not work correctly when the config value `general.idle_threshold` updates to `"none"` after application's startup because of wayland protocol's work.
Now this case handles carefully and should work correctly.
> fix: handle case when idle_threshold == 0 during re-creation

- Cargo.lock
- Cargo.toml
- crates/backend/Cargo.toml
- crates/client/Cargo.toml
- crates/config/Cargo.toml
- crates/dbus/Cargo.toml
- crates/filetype/Cargo.toml
- crates/macros/Cargo.toml
- crates/render/Cargo.toml
- crates/shared/Cargo.toml
The syntax `package = { workspase = true }` looks longer and dirtier than `package.workspace = true`, so I wanted to clean curly braces with short syntax.
Reorganized packages. Now for every crate the packages was split in three groups:
- workspace members as dependencies;
- foreign crates as workspace dependencies;
- local dependencies.
With it, as I mentioned in [motivation](#motivation), the syntax became shorter and more cleaner than previously. Also the syntax `package = { path = "..." }` was reduced to `package.path = "..."`.
> refactor: clean Cargo.toml's files

- crates/config/src/spacing.rs
- crates/filetype/src/converter.rs
- crates/filetype/src/layout.pest
- crates/macros/src/config_property.rs
- crates/macros/src/general.rs
- crates/macros/src/generic_builder.rs
- crates/macros/tests/generic_builder.rs
- crates/render/src/widget/flex_container.rs
- crates/shared/src/error.rs
- crates/shared/src/value.rs
The syntax `Spacing(top = 10, bottom = 10, left = 5, right = 5)` is annoying to declare because or repeating and it's also applicable for `Spacing(top = 5, bottom = 5, left = 5, right = 5)`. Therefore, need to something that should help write less information but achieve the same result.
- The `Value` enum type is now extended by availability to `clone`. It's optional but urgent for assignment the same value for different fields. Of course, for single field the `clone` characteristic will not be used, so don't worry about it.
- Introduced the `alias` of field. Some fields can have the same aliases and it means that for this alias value will assigned for these fields.
- Introduced the `constructor` syntax. If the struct is homogeneous (have the same types of all fields), it can possibility …
> feat: extend gbuilder by aliases and constructor

- Cargo.lock
- crates/render/Cargo.toml
- crates/render/src/font.rs
- crates/render/src/image.rs
I found that the Rust allocator is not good for large fonts (or for large data). I don't know why, but the allocator doesn't deallocate the memory in moment because it will be helpful for other parts of application. I call it "reusing".
And as I said, it is bad for large data because after its drop the small parts will use the allocated memory and it won't be enough for next large data. Because of this new allocation will happens. The memory usage will growth more and more. For instance, the `FontCollection` struct drops and new `FontCollections` creates when an user changes the font name in config file. The other font file will have different size. Then when the user decides to switch back to old font name, the owned size is not matches (may be larger than available). So it will cause an …
> fix: use libc allocator for fonts and add math font fallback

- Cargo.toml
Reduce the binary size from 14mb to 6.1 in average without breaking.
> chore(cargo): override release profile to focus on min size of binary
